### ISSUE TITLE
Generalize inverse transform

### ISSUE THREAD

**Issue by aalbaali** [aalbaali/TransformsGraph#7]
As of now, the `TransformsGraph` object requires that the `Transform` has an internal function `Transform::inverse()`. This is restrictive and invasive.

Generalize the `TransformsGraph` such that the inverse function is *injected* into the `TransformsGraph`, which should be done using `std::bind`, lambdas, or `std::function`.

# TODO
- [x] Update the `TransformsGraph` and ensure all tests pass
- [x] Update the documentation
- [x] Update the examples so they don't need the `inverse` member function to be explicitly defined inside the transform class
